from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class ContenidoPieza(Base):
    """Content piece generated by IA for a dirigente.

    Stores multi-platform variants (Twitter, Instagram Reel, etc.)
    with full traceability: model used, prompt, token count.
    """

    __tablename__ = "contenido_piezas"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    org_id: Mapped[int] = mapped_column(
        ForeignKey("organizaciones.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    dirigente_id: Mapped[int] = mapped_column(
        ForeignKey("dirigentes.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    tema: Mapped[str] = mapped_column(String(500), nullable=False)
    contexto: Mapped[str | None] = mapped_column(Text, nullable=True)
    tono: Mapped[str] = mapped_column(String(50), default="propositivo", nullable=False)
    variantes: Mapped[dict] = mapped_column(JSONB, nullable=False)
    modelo_ia: Mapped[str] = mapped_column(String(100), nullable=False)
    prompt_usado: Mapped[str] = mapped_column(Text, nullable=False)
    tokens_usados: Mapped[int | None] = mapped_column(Integer, nullable=True)
    estado: Mapped[str] = mapped_column(String(50), default="borrador", nullable=False)
    aprobado_por: Mapped[int | None] = mapped_column(
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    aprobado_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    programacion: Mapped[dict | None] = mapped_column(JSONB, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )

    # ── Relationships ────────────────────────────────────
    organizacion = relationship("Organizacion", lazy="selectin")
    dirigente = relationship("Dirigente", lazy="selectin")
    aprobador = relationship("User", lazy="selectin", foreign_keys=[aprobado_por])
