from __future__ import annotations

from datetime import UTC, datetime

from sqlalchemy import BigInteger, Boolean, DateTime, ForeignKey, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class IaContentRegistry(Base):
    """Registry for all IA-generated content for INE compliance.

    Every piece of content generated by AI must be registered here
    with the model used, a hash of the prompt, and publication status.
    Required for electoral transparency and legal compliance (modo veda).
    """

    __tablename__ = "ia_content_registry"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    org_id: Mapped[int] = mapped_column(
        ForeignKey("organizaciones.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    tipo_contenido: Mapped[str] = mapped_column(String(100), nullable=False)
    referencia_tabla: Mapped[str] = mapped_column(String(100), nullable=False)
    referencia_id: Mapped[str] = mapped_column(String(100), nullable=False)
    modelo_ia: Mapped[str] = mapped_column(String(100), nullable=False)
    prompt_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    publicado: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        nullable=False,
    )

    # ── Relationships ────────────────────────────────────
    organizacion = relationship("Organizacion", lazy="selectin")
