"""
Fix duplicate dirigentes generated by patch_add_3_users_2026_05_29.

Carlos's BD ya tenía dirigentes preexistentes para Felipe (Felipe de Jesús
Martínez Gallegos), Laura (variante c/s Mancilla) y Pepe (posiblemente como
José Monroy o variante). Mi patch script creó duplicados porque buscaba
full_name por exact match.

Este script auto-descubre el duplicado por nombre parcial, re-apunta el
user al registro CANÓNICO (preexistente, con más data scrapeada), borra
el duplicado que yo creé y normaliza users.full_name al nombre del
canónico (para sidebar/UI consistency).

Dry-run por default. Para aplicar:
    python -m scripts.fix_dirigente_dups_2026_05_29 --apply

Idempotente: si los duplicados ya fueron limpiados, no hace nada.
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from sqlalchemy import delete, select, update
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from sqlalchemy.orm import sessionmaker

from app.core.config import settings
from app.models.dirigente import Dirigente
from app.models.user import User


# Cada tupla: (email del user, patrón ILIKE para encontrar al canónico)
# Los patrones son intencionalmente específicos para evitar capturar otros
# Martínez/Monroy que no sean los dirigentes del piloto.
TARGETS = [
    ("ballesteros@crece.mx", "%Ballesteros%"),
    ("pmonroy@paz.mx",       "%Monroy%"),
    ("martinez@crece.mx",    "%Felipe%Mart%"),
]


async def fix(apply: bool) -> None:
    engine = create_async_engine(settings.DATABASE_URL)
    Session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)

    async with Session() as session:
        for email, pattern in TARGETS:
            print(f"\n── {email}  (patrón ILIKE '{pattern}') ──")
            user = await session.scalar(select(User).where(User.email == email))
            if not user:
                print(f"  WARN: user no existe; saltando.")
                continue

            current = await session.scalar(
                select(Dirigente).where(Dirigente.id == user.dirigente_id)
            )
            if not current:
                print(f"  WARN: user apunta a dirigente_id={user.dirigente_id} pero ese dirigente no existe.")
                continue

            candidates = (await session.scalars(
                select(Dirigente)
                .where(Dirigente.full_name.ilike(pattern))
                .where(Dirigente.id != current.id)
                .order_by(Dirigente.id)
            )).all()

            print(f"  current (linked to user): id={current.id}  '{current.full_name}'")
            print(f"  candidatos canónicos ({len(candidates)}):")
            for c in candidates:
                print(f"    - id={c.id}  '{c.full_name}'  cargo='{c.cargo}'")

            if len(candidates) == 0:
                print(f"  → sin duplicado detectado; nada que hacer.")
                continue
            if len(candidates) > 1:
                print(f"  → MÚLTIPLES candidatos; revisión manual requerida. NO toco esto.")
                continue

            canonical = candidates[0]
            print(f"  → Plan: re-apuntar user.dirigente_id de {current.id} → {canonical.id},")
            print(f"           actualizar user.full_name → '{canonical.full_name}',")
            print(f"           borrar dirigente duplicado id={current.id} ('{current.full_name}').")

            if not apply:
                print(f"  (dry-run; sin cambios)")
                continue

            await session.execute(
                update(User)
                .where(User.id == user.id)
                .values(dirigente_id=canonical.id, full_name=canonical.full_name)
            )
            await session.execute(
                delete(Dirigente).where(Dirigente.id == current.id)
            )
            print(f"  ✓ aplicado.")

        if apply:
            await session.commit()
            print("\nCommit OK.")
        else:
            print("\n(dry-run · ningún cambio escrito · re-corre con --apply para confirmar)")

    await engine.dispose()


if __name__ == "__main__":
    apply_flag = "--apply" in sys.argv
    asyncio.run(fix(apply_flag))
