"""add_resultados_electorales_seccion_2024

Revision ID: 3d6fe3f1660d
Revises: ds04_matrix_context
Create Date: 2026-04-15 16:12:52.373133
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d6fe3f1660d'
down_revision: Union[str, None] = 'ds04_matrix_context'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados_electorales_seccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seccion_clave', sa.String(length=10), nullable=False),
    sa.Column('id_entidad', sa.SmallInteger(), nullable=False),
    sa.Column('entidad', sa.String(length=100), nullable=False),
    sa.Column('seccion', sa.Integer(), nullable=False),
    sa.Column('municipio', sa.String(length=200), nullable=True),
    sa.Column('eleccion', sa.String(length=50), nullable=False),
    sa.Column('votos_pan', sa.Integer(), nullable=False),
    sa.Column('votos_pri', sa.Integer(), nullable=False),
    sa.Column('votos_prd', sa.Integer(), nullable=False),
    sa.Column('votos_pvem', sa.Integer(), nullable=False),
    sa.Column('votos_pt', sa.Integer(), nullable=False),
    sa.Column('votos_mc', sa.Integer(), nullable=False),
    sa.Column('votos_morena', sa.Integer(), nullable=False),
    sa.Column('votos_nulos', sa.Integer(), nullable=False),
    sa.Column('total_votos', sa.Integer(), nullable=False),
    sa.Column('lista_nominal', sa.Integer(), nullable=False),
    sa.Column('mc_share', sa.Float(), nullable=True),
    sa.Column('margen_mc', sa.Float(), nullable=True),
    sa.Column('seccion_electoral_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seccion_electoral_id'], ['secciones_electorales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seccion_clave', 'eleccion', name='uq_resultados_seccion_eleccion')
    )
    op.create_index(op.f('ix_resultados_electorales_seccion_id_entidad'), 'resultados_electorales_seccion', ['id_entidad'], unique=False)
    op.create_index(op.f('ix_resultados_electorales_seccion_seccion_clave'), 'resultados_electorales_seccion', ['seccion_clave'], unique=False)
    op.create_index(op.f('ix_resultados_electorales_seccion_seccion_electoral_id'), 'resultados_electorales_seccion', ['seccion_electoral_id'], unique=False)
    op.drop_index(op.f('ix_contexto_ambito_entidad'), table_name='contexto_politico')
    op.drop_table('contexto_politico')
    op.drop_index(op.f('ix_framework_audit_org'), table_name='framework_audit_log')
    op.drop_table('framework_audit_log')
    op.drop_index(op.f('distritos_federales_oaxaca_geom_geom_idx'), table_name='distritos_federales_oaxaca', postgresql_using='gist')
    op.drop_table('distritos_federales_oaxaca')
    op.drop_index(op.f('distritos_locales_cdmx_geom_geom_idx'), table_name='distritos_locales_cdmx', postgresql_using='gist')
    op.drop_table('distritos_locales_cdmx')
    op.drop_index(op.f('secciones_geo_cdmx_geom_geom_idx'), table_name='secciones_geo_cdmx', postgresql_using='gist')
    op.drop_table('secciones_geo_cdmx')
    op.drop_index(op.f('distritos_federales_cdmx_geom_geom_idx'), table_name='distritos_federales_cdmx', postgresql_using='gist')
    op.drop_table('distritos_federales_cdmx')
    op.drop_index(op.f('ix_dal_action'), table_name='data_access_log')
    op.drop_index(op.f('ix_dal_created_at'), table_name='data_access_log')
    op.drop_index(op.f('ix_dal_org_id'), table_name='data_access_log')
    op.drop_index(op.f('ix_dal_table_row'), table_name='data_access_log')
    op.drop_index(op.f('ix_dal_user_id'), table_name='data_access_log')
    op.drop_table('data_access_log')
    op.drop_index(op.f('ix_social_comments_author_hash'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_author_hash_post'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_data_source'), table_name='social_comments', postgresql_where='(data_source IS NOT NULL)')
    op.drop_index(op.f('ix_social_comments_parent_post_id'), table_name='social_comments')
    op.drop_index(op.f('ix_social_comments_published_at'), table_name='social_comments')
    op.drop_table('social_comments')
    op.drop_index(op.f('ix_framework_overrides_org'), table_name='framework_overrides_org')
    op.drop_table('framework_overrides_org')
    op.drop_table('framework_matrix_defaults')
    op.drop_index(op.f('ix_encuestas_publicas_actor'), table_name='encuestas_publicas')
    op.drop_index(op.f('ix_encuestas_publicas_ambito_entidad'), table_name='encuestas_publicas')
    op.drop_index(op.f('ix_encuestas_publicas_fecha'), table_name='encuestas_publicas')
    op.drop_table('encuestas_publicas')
    op.drop_index(op.f('distritos_locales_oaxaca_geom_geom_idx'), table_name='distritos_locales_oaxaca', postgresql_using='gist')
    op.drop_table('distritos_locales_oaxaca')
    op.drop_index(op.f('secciones_geo_oaxaca_geom_geom_idx'), table_name='secciones_geo_oaxaca', postgresql_using='gist')
    op.drop_table('secciones_geo_oaxaca')
    op.drop_index(op.f('ix_alcaldias_cdmx_geom'), table_name='alcaldias_cdmx', postgresql_using='gist')
    op.drop_constraint(op.f('uq_alcaldias_cdmx_cvegeo'), 'alcaldias_cdmx', type_='unique')
    op.drop_constraint(op.f('uq_alcaldias_cdmx_nombre'), 'alcaldias_cdmx', type_='unique')
    op.drop_index(op.f('ix_alcaldias_cdmx_cvegeo'), table_name='alcaldias_cdmx')
    op.create_index(op.f('ix_alcaldias_cdmx_cvegeo'), 'alcaldias_cdmx', ['cvegeo'], unique=True)
    op.drop_index(op.f('ix_alcaldias_cdmx_nombre'), table_name='alcaldias_cdmx')
    op.create_index(op.f('ix_alcaldias_cdmx_nombre'), 'alcaldias_cdmx', ['nombre'], unique=True)
    op.drop_index(op.f('ix_ciudadanos_legacy_deleted_at'), table_name='ciudadanos_legacy', postgresql_where='(deleted_at IS NOT NULL)')
    op.drop_index(op.f('ix_cl_alcaldia_id'), table_name='ciudadanos_legacy')
    op.drop_index(op.f('ix_cl_legacy_id'), table_name='ciudadanos_legacy')
    op.drop_index(op.f('ix_cl_org_id'), table_name='ciudadanos_legacy')
    op.drop_index(op.f('ix_cl_promotor_legacy_id'), table_name='ciudadanos_legacy')
    op.drop_index(op.f('ix_cl_seccion'), table_name='ciudadanos_legacy')
    op.drop_index(op.f('ix_cl_unidad_territorial_id'), table_name='ciudadanos_legacy')
    op.drop_constraint(op.f('uq_cl_legacy_id'), 'ciudadanos_legacy', type_='unique')
    op.create_index(op.f('ix_ciudadanos_legacy_alcaldia_id'), 'ciudadanos_legacy', ['alcaldia_id'], unique=False)
    op.create_index(op.f('ix_ciudadanos_legacy_legacy_id'), 'ciudadanos_legacy', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_ciudadanos_legacy_org_id'), 'ciudadanos_legacy', ['org_id'], unique=False)
    op.create_index(op.f('ix_ciudadanos_legacy_promotor_legacy_id'), 'ciudadanos_legacy', ['promotor_legacy_id'], unique=False)
    op.create_index(op.f('ix_ciudadanos_legacy_seccion'), 'ciudadanos_legacy', ['seccion'], unique=False)
    op.create_index(op.f('ix_ciudadanos_legacy_unidad_territorial_id'), 'ciudadanos_legacy', ['unidad_territorial_id'], unique=False)
    op.drop_column('ciudadanos_legacy', 'clave_electoral_enc')
    op.drop_column('ciudadanos_legacy', 'whatsapp_enc')
    op.drop_column('ciudadanos_legacy', 'phone_02_enc')
    op.drop_column('ciudadanos_legacy', 'phone_01_enc')
    op.drop_column('ciudadanos_legacy', 'email_enc')
    op.drop_column('ciudadanos_legacy', 'fecha_nacimiento_enc')
    op.drop_column('competidor_social_profiles', 'last_scraped_at')
    op.drop_index(op.f('ix_dirigentes_sync_status'), table_name='dirigentes')
    op.drop_column('dirigentes', 'rol_politico')
    op.drop_index(op.f('ix_pl_alcaldia_id'), table_name='promotores_legacy')
    op.drop_index(op.f('ix_pl_legacy_user_id'), table_name='promotores_legacy')
    op.drop_index(op.f('ix_pl_org_id'), table_name='promotores_legacy')
    op.drop_index(op.f('ix_pl_user_name'), table_name='promotores_legacy')
    op.drop_constraint(op.f('uq_pl_legacy_user_id'), 'promotores_legacy', type_='unique')
    op.drop_constraint(op.f('uq_pl_user_name'), 'promotores_legacy', type_='unique')
    op.create_index(op.f('ix_promotores_legacy_alcaldia_id'), 'promotores_legacy', ['alcaldia_id'], unique=False)
    op.create_index(op.f('ix_promotores_legacy_legacy_user_id'), 'promotores_legacy', ['legacy_user_id'], unique=True)
    op.create_index(op.f('ix_promotores_legacy_org_id'), 'promotores_legacy', ['org_id'], unique=False)
    op.create_index(op.f('ix_promotores_legacy_user_name'), 'promotores_legacy', ['user_name'], unique=True)
    op.drop_index(op.f('ix_secciones_electorales_seccion'), table_name='secciones_electorales')
    op.create_index(op.f('ix_secciones_electorales_seccion'), 'secciones_electorales', ['seccion'], unique=False)
    op.drop_column('social_posts', 'tono_discurso')
    op.drop_column('social_posts', 'controversy_score')
    op.drop_column('social_posts', 'sentimiento_politico_ajustado')
    op.drop_column('social_posts', 'llm_processed_at')
    op.drop_column('social_posts', 'llm_razon')
    op.drop_column('social_posts', 'target_politico')
    op.drop_column('social_posts', 'nlp_model_version')
    op.drop_column('social_posts', 'toxicity_score')
    op.drop_column('social_posts', 'platform_adjusted_sentiment')
    op.drop_column('social_posts', 'llm_modelo')
    op.drop_column('social_posts', 'topics_jsonb')
    op.drop_index(op.f('ix_snapshots_dirigente_taken'), table_name='social_profile_snapshots')
    op.drop_index(op.f('ix_snapshots_org_platform_taken'), table_name='social_profile_snapshots')
    op.drop_index(op.f('ix_snapshots_profile_taken'), table_name='social_profile_snapshots')
    op.create_index(op.f('ix_social_profile_snapshots_dirigente_id'), 'social_profile_snapshots', ['dirigente_id'], unique=False)
    op.create_index(op.f('ix_social_profile_snapshots_org_id'), 'social_profile_snapshots', ['org_id'], unique=False)
    op.create_index(op.f('ix_social_profile_snapshots_platform'), 'social_profile_snapshots', ['platform'], unique=False)
    op.create_index(op.f('ix_social_profile_snapshots_profile_id'), 'social_profile_snapshots', ['profile_id'], unique=False)
    op.create_index(op.f('ix_social_profile_snapshots_taken_at'), 'social_profile_snapshots', ['taken_at'], unique=False)
    op.drop_index(op.f('ix_topic_trends_embedding_hnsw'), table_name='topic_trends', postgresql_ops={'topic_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_topic_trends_org_alcaldia_bucket'), table_name='topic_trends')
    op.drop_index(op.f('ix_ut_alcaldia_id'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_ut_alcaldia_nombre'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_ut_categoria'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_ut_circunscripcion_2024'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_ut_clave_unidad_territorial'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_ut_estrato'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_ut_legacy_id'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_ut_seccion_2024'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_ut_volatilidad'), table_name='unidades_territoriales')
    op.drop_constraint(op.f('uq_ut_legacy_id'), 'unidades_territoriales', type_='unique')
    op.create_index(op.f('ix_unidades_territoriales_alcaldia_id'), 'unidades_territoriales', ['alcaldia_id'], unique=False)
    op.create_index(op.f('ix_unidades_territoriales_alcaldia_nombre'), 'unidades_territoriales', ['alcaldia_nombre'], unique=False)
    op.create_index(op.f('ix_unidades_territoriales_categoria'), 'unidades_territoriales', ['categoria'], unique=False)
    op.create_index(op.f('ix_unidades_territoriales_circunscripcion_2024'), 'unidades_territoriales', ['circunscripcion_2024'], unique=False)
    op.create_index(op.f('ix_unidades_territoriales_clave_unidad_territorial'), 'unidades_territoriales', ['clave_unidad_territorial'], unique=False)
    op.create_index(op.f('ix_unidades_territoriales_estrato'), 'unidades_territoriales', ['estrato'], unique=False)
    op.create_index(op.f('ix_unidades_territoriales_legacy_id'), 'unidades_territoriales', ['legacy_id'], unique=True)
    op.create_index(op.f('ix_unidades_territoriales_seccion_2024'), 'unidades_territoriales', ['seccion_2024'], unique=False)
    op.create_index(op.f('ix_unidades_territoriales_volatilidad'), 'unidades_territoriales', ['volatilidad'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_unidades_territoriales_volatilidad'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_unidades_territoriales_seccion_2024'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_unidades_territoriales_legacy_id'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_unidades_territoriales_estrato'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_unidades_territoriales_clave_unidad_territorial'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_unidades_territoriales_circunscripcion_2024'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_unidades_territoriales_categoria'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_unidades_territoriales_alcaldia_nombre'), table_name='unidades_territoriales')
    op.drop_index(op.f('ix_unidades_territoriales_alcaldia_id'), table_name='unidades_territoriales')
    op.create_unique_constraint(op.f('uq_ut_legacy_id'), 'unidades_territoriales', ['legacy_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_ut_volatilidad'), 'unidades_territoriales', ['volatilidad'], unique=False)
    op.create_index(op.f('ix_ut_seccion_2024'), 'unidades_territoriales', ['seccion_2024'], unique=False)
    op.create_index(op.f('ix_ut_legacy_id'), 'unidades_territoriales', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_ut_estrato'), 'unidades_territoriales', ['estrato'], unique=False)
    op.create_index(op.f('ix_ut_clave_unidad_territorial'), 'unidades_territoriales', ['clave_unidad_territorial'], unique=False)
    op.create_index(op.f('ix_ut_circunscripcion_2024'), 'unidades_territoriales', ['circunscripcion_2024'], unique=False)
    op.create_index(op.f('ix_ut_categoria'), 'unidades_territoriales', ['categoria'], unique=False)
    op.create_index(op.f('ix_ut_alcaldia_nombre'), 'unidades_territoriales', ['alcaldia_nombre'], unique=False)
    op.create_index(op.f('ix_ut_alcaldia_id'), 'unidades_territoriales', ['alcaldia_id'], unique=False)
    op.create_index(op.f('ix_topic_trends_org_alcaldia_bucket'), 'topic_trends', ['org_id', 'alcaldia_id', 'time_bucket'], unique=False)
    op.create_index(op.f('ix_topic_trends_embedding_hnsw'), 'topic_trends', ['topic_embedding'], unique=False, postgresql_ops={'topic_embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_social_profile_snapshots_taken_at'), table_name='social_profile_snapshots')
    op.drop_index(op.f('ix_social_profile_snapshots_profile_id'), table_name='social_profile_snapshots')
    op.drop_index(op.f('ix_social_profile_snapshots_platform'), table_name='social_profile_snapshots')
    op.drop_index(op.f('ix_social_profile_snapshots_org_id'), table_name='social_profile_snapshots')
    op.drop_index(op.f('ix_social_profile_snapshots_dirigente_id'), table_name='social_profile_snapshots')
    op.create_index(op.f('ix_snapshots_profile_taken'), 'social_profile_snapshots', ['profile_id', 'taken_at'], unique=False)
    op.create_index(op.f('ix_snapshots_org_platform_taken'), 'social_profile_snapshots', ['org_id', 'platform', 'taken_at'], unique=False)
    op.create_index(op.f('ix_snapshots_dirigente_taken'), 'social_profile_snapshots', ['dirigente_id', 'taken_at'], unique=False)
    op.add_column('social_posts', sa.Column('topics_jsonb', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('llm_modelo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('platform_adjusted_sentiment', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('toxicity_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('nlp_model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('target_politico', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('llm_razon', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('llm_processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('sentimiento_politico_ajustado', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('controversy_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('social_posts', sa.Column('tono_discurso', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_secciones_electorales_seccion'), table_name='secciones_electorales')
    op.create_index(op.f('ix_secciones_electorales_seccion'), 'secciones_electorales', ['seccion'], unique=True)
    op.drop_index(op.f('ix_promotores_legacy_user_name'), table_name='promotores_legacy')
    op.drop_index(op.f('ix_promotores_legacy_org_id'), table_name='promotores_legacy')
    op.drop_index(op.f('ix_promotores_legacy_legacy_user_id'), table_name='promotores_legacy')
    op.drop_index(op.f('ix_promotores_legacy_alcaldia_id'), table_name='promotores_legacy')
    op.create_unique_constraint(op.f('uq_pl_user_name'), 'promotores_legacy', ['user_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_pl_legacy_user_id'), 'promotores_legacy', ['legacy_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pl_user_name'), 'promotores_legacy', ['user_name'], unique=False)
    op.create_index(op.f('ix_pl_org_id'), 'promotores_legacy', ['org_id'], unique=False)
    op.create_index(op.f('ix_pl_legacy_user_id'), 'promotores_legacy', ['legacy_user_id'], unique=False)
    op.create_index(op.f('ix_pl_alcaldia_id'), 'promotores_legacy', ['alcaldia_id'], unique=False)
    op.add_column('dirigentes', sa.Column('rol_politico', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_dirigentes_sync_status'), 'dirigentes', ['sync_status'], unique=False)
    op.add_column('competidor_social_profiles', sa.Column('last_scraped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('ciudadanos_legacy', sa.Column('fecha_nacimiento_enc', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('ciudadanos_legacy', sa.Column('email_enc', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('ciudadanos_legacy', sa.Column('phone_01_enc', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('ciudadanos_legacy', sa.Column('phone_02_enc', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('ciudadanos_legacy', sa.Column('whatsapp_enc', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.add_column('ciudadanos_legacy', sa.Column('clave_electoral_enc', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_ciudadanos_legacy_unidad_territorial_id'), table_name='ciudadanos_legacy')
    op.drop_index(op.f('ix_ciudadanos_legacy_seccion'), table_name='ciudadanos_legacy')
    op.drop_index(op.f('ix_ciudadanos_legacy_promotor_legacy_id'), table_name='ciudadanos_legacy')
    op.drop_index(op.f('ix_ciudadanos_legacy_org_id'), table_name='ciudadanos_legacy')
    op.drop_index(op.f('ix_ciudadanos_legacy_legacy_id'), table_name='ciudadanos_legacy')
    op.drop_index(op.f('ix_ciudadanos_legacy_alcaldia_id'), table_name='ciudadanos_legacy')
    op.create_unique_constraint(op.f('uq_cl_legacy_id'), 'ciudadanos_legacy', ['legacy_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_cl_unidad_territorial_id'), 'ciudadanos_legacy', ['unidad_territorial_id'], unique=False)
    op.create_index(op.f('ix_cl_seccion'), 'ciudadanos_legacy', ['seccion'], unique=False)
    op.create_index(op.f('ix_cl_promotor_legacy_id'), 'ciudadanos_legacy', ['promotor_legacy_id'], unique=False)
    op.create_index(op.f('ix_cl_org_id'), 'ciudadanos_legacy', ['org_id'], unique=False)
    op.create_index(op.f('ix_cl_legacy_id'), 'ciudadanos_legacy', ['legacy_id'], unique=False)
    op.create_index(op.f('ix_cl_alcaldia_id'), 'ciudadanos_legacy', ['alcaldia_id'], unique=False)
    op.create_index(op.f('ix_ciudadanos_legacy_deleted_at'), 'ciudadanos_legacy', ['deleted_at'], unique=False, postgresql_where='(deleted_at IS NOT NULL)')
    op.drop_index(op.f('ix_alcaldias_cdmx_nombre'), table_name='alcaldias_cdmx')
    op.create_index(op.f('ix_alcaldias_cdmx_nombre'), 'alcaldias_cdmx', ['nombre'], unique=False)
    op.drop_index(op.f('ix_alcaldias_cdmx_cvegeo'), table_name='alcaldias_cdmx')
    op.create_index(op.f('ix_alcaldias_cdmx_cvegeo'), 'alcaldias_cdmx', ['cvegeo'], unique=False)
    op.create_unique_constraint(op.f('uq_alcaldias_cdmx_nombre'), 'alcaldias_cdmx', ['nombre'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_alcaldias_cdmx_cvegeo'), 'alcaldias_cdmx', ['cvegeo'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_alcaldias_cdmx_geom'), 'alcaldias_cdmx', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('secciones_geo_oaxaca',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.NUMERIC(precision=23, scale=15), autoincrement=False, nullable=True),
    sa.Column('entidad', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('distrito_f', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('distrito_l', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('municipio', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('seccion', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('control', sa.NUMERIC(precision=23, scale=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name=op.f('secciones_geo_oaxaca_pkey'))
    )
    op.create_index(op.f('secciones_geo_oaxaca_geom_geom_idx'), 'secciones_geo_oaxaca', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('distritos_locales_oaxaca',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('entidad', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('distrito_l', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name=op.f('distritos_locales_oaxaca_pkey'))
    )
    op.create_index(op.f('distritos_locales_oaxaca_geom_geom_idx'), 'distritos_locales_oaxaca', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('encuestas_publicas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fuente', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fecha_publicacion', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('ambito', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('entidad', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('actor_tipo', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('actor_nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('actor_partido', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('metrica', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('valor_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('valor_delta_vs_anterior', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('tamaño_muestra', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('margen_error', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('url_fuente', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('encuestas_publicas_pkey'))
    )
    op.create_index(op.f('ix_encuestas_publicas_fecha'), 'encuestas_publicas', ['fecha_publicacion'], unique=False)
    op.create_index(op.f('ix_encuestas_publicas_ambito_entidad'), 'encuestas_publicas', ['ambito', 'entidad'], unique=False)
    op.create_index(op.f('ix_encuestas_publicas_actor'), 'encuestas_publicas', ['actor_nombre'], unique=False)
    op.create_table('framework_matrix_defaults',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tono', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('target', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('score_politico', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('contexto', sa.VARCHAR(length=20), server_default=sa.text("'post_dirigente'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('framework_matrix_defaults_pkey')),
    sa.UniqueConstraint('version', 'rol', 'tono', 'target', 'contexto', name=op.f('uq_framework_defaults_v2'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('framework_overrides_org',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tono', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('target', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('score_politico', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('modified_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modified_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['modified_by_user_id'], ['users.id'], name=op.f('framework_overrides_org_modified_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], name=op.f('framework_overrides_org_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('framework_overrides_org_pkey')),
    sa.UniqueConstraint('org_id', 'rol', 'tono', 'target', name=op.f('uq_framework_overrides'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_framework_overrides_org'), 'framework_overrides_org', ['org_id'], unique=False)
    op.create_table('social_comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform_comment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('author_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('likes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('nlp_tono', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('nlp_target', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('nlp_polaridad', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('nlp_model_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_reply_to_comment', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('parent_comment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('es_follower', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['social_comments.id'], name=op.f('social_comments_parent_comment_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_post_id'], ['social_posts.id'], name=op.f('social_comments_parent_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('social_comments_pkey')),
    sa.UniqueConstraint('platform_comment_id', name=op.f('social_comments_platform_comment_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_social_comments_published_at'), 'social_comments', ['published_at'], unique=False)
    op.create_index(op.f('ix_social_comments_parent_post_id'), 'social_comments', ['parent_post_id'], unique=False)
    op.create_index(op.f('ix_social_comments_data_source'), 'social_comments', ['data_source'], unique=False, postgresql_where='(data_source IS NOT NULL)')
    op.create_index(op.f('ix_social_comments_author_hash_post'), 'social_comments', ['author_hash', 'parent_post_id'], unique=False)
    op.create_index(op.f('ix_social_comments_author_hash'), 'social_comments', ['author_hash'], unique=False)
    op.create_table('data_access_log',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('row_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='read_pii | decrypt | delete_gdpr | export'),
    sa.Column('fields', postgresql.ARRAY(sa.VARCHAR(length=50)), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('request_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('data_access_log_pkey'))
    )
    op.create_index(op.f('ix_dal_user_id'), 'data_access_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_dal_table_row'), 'data_access_log', ['table_name', 'row_id'], unique=False)
    op.create_index(op.f('ix_dal_org_id'), 'data_access_log', ['org_id'], unique=False)
    op.create_index(op.f('ix_dal_created_at'), 'data_access_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_dal_action'), 'data_access_log', ['action'], unique=False)
    op.create_table('distritos_federales_cdmx',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.NUMERIC(precision=23, scale=15), autoincrement=False, nullable=True),
    sa.Column('entidad', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('distrito_f', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('control', sa.NUMERIC(precision=23, scale=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name=op.f('distritos_federales_cdmx_pkey'))
    )
    op.create_index(op.f('distritos_federales_cdmx_geom_geom_idx'), 'distritos_federales_cdmx', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('secciones_geo_cdmx',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id', sa.NUMERIC(precision=23, scale=15), autoincrement=False, nullable=True),
    sa.Column('entidad', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('distrito_f', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('distrito_l', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('municipio', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('seccion', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('control', sa.NUMERIC(precision=23, scale=15), autoincrement=False, nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('volatilidad', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estrato', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('lista_nominal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('dtto_local_cat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dtto_fed_cat', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alcaldia', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('nivel_socioeconomico', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name=op.f('secciones_geo_cdmx_pkey'))
    )
    op.create_index(op.f('secciones_geo_cdmx_geom_geom_idx'), 'secciones_geo_cdmx', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('distritos_locales_cdmx',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('entidad', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('distrito_l', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name=op.f('distritos_locales_cdmx_pkey'))
    )
    op.create_index(op.f('distritos_locales_cdmx_geom_geom_idx'), 'distritos_locales_cdmx', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('distritos_federales_oaxaca',
    sa.Column('gid', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.NUMERIC(precision=23, scale=15), autoincrement=False, nullable=True),
    sa.Column('entidad', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('distrito_f', sa.NUMERIC(precision=18, scale=0), autoincrement=False, nullable=True),
    sa.Column('control', sa.NUMERIC(precision=23, scale=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('gid', name=op.f('distritos_federales_oaxaca_pkey'))
    )
    op.create_index(op.f('distritos_federales_oaxaca_geom_geom_idx'), 'distritos_federales_oaxaca', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('framework_audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tono', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('target', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('score_before', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('score_after', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('score_default', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('razon', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('framework_audit_log_changed_by_user_id_fkey')),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], name=op.f('framework_audit_log_org_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('framework_audit_log_pkey'))
    )
    op.create_index(op.f('ix_framework_audit_org'), 'framework_audit_log', ['org_id'], unique=False)
    op.create_table('contexto_politico',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ambito', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('entidad', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('partido_gobernante', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('vigente_desde', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('vigente_hasta', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('contexto_politico_pkey'))
    )
    op.create_index(op.f('ix_contexto_ambito_entidad'), 'contexto_politico', ['ambito', 'entidad'], unique=False)
    op.drop_index(op.f('ix_resultados_electorales_seccion_seccion_electoral_id'), table_name='resultados_electorales_seccion')
    op.drop_index(op.f('ix_resultados_electorales_seccion_seccion_clave'), table_name='resultados_electorales_seccion')
    op.drop_index(op.f('ix_resultados_electorales_seccion_id_entidad'), table_name='resultados_electorales_seccion')
    op.drop_table('resultados_electorales_seccion')
    # ### end Alembic commands ###
