"""fase 2 — campaigns, canvassing, contenido, voter scores, compliance, participacion

Revision ID: 77a614d10263
Revises: 77bbd5e5f495
Create Date: 2026-04-03 20:59:39.495144
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77a614d10263'
down_revision: Union[str, None] = '77bbd5e5f495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertas_compliance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('GASTO_SIN_FACTURA', 'GASTO_EXCEDE_TOPE', 'BOT_DETECTADO', 'CONTENIDO_SIN_ETIQUETA_IA', 'VEDA_VIOLACION', 'ENGAGEMENT_ANOMALO', 'TOPE_CAMPANA_PROXIMO', name='tipo_alerta_compliance'), nullable=False),
    sa.Column('severidad', sa.Enum('CRITICA', 'ALTA', 'MEDIA', 'BAJA', name='severidad_alerta'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=False),
    sa.Column('referencia_id', sa.Integer(), nullable=True),
    sa.Column('resuelta', sa.Boolean(), nullable=False),
    sa.Column('resuelta_por_id', sa.Integer(), nullable=True),
    sa.Column('resuelta_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resuelta_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_compliance_org_id'), 'alertas_compliance', ['org_id'], unique=False)
    op.create_table('campanas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('MASIVA', 'SEGMENTADA', 'INDIVIDUAL', name='tipo_campana'), nullable=False),
    sa.Column('plantilla_mensaje', sa.Text(), nullable=False),
    sa.Column('variables_plantilla', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.Enum('BORRADOR', 'PROGRAMADA', 'ENVIANDO', 'COMPLETADA', 'CANCELADA', name='estado_campana'), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_completada', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('dirigente_id', sa.Integer(), nullable=True),
    sa.Column('total_destinatarios', sa.Integer(), nullable=False),
    sa.Column('total_enviados', sa.Integer(), nullable=False),
    sa.Column('total_entregados', sa.Integer(), nullable=False),
    sa.Column('total_leidos', sa.Integer(), nullable=False),
    sa.Column('total_respondidos', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dirigente_id'], ['dirigentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campanas_dirigente_id'), 'campanas', ['dirigente_id'], unique=False)
    op.create_index(op.f('ix_campanas_nombre'), 'campanas', ['nombre'], unique=False)
    op.create_index(op.f('ix_campanas_org_id'), 'campanas', ['org_id'], unique=False)
    op.create_table('contenidos_generados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dirigente_id', sa.Integer(), nullable=False),
    sa.Column('generado_por_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('formato', sa.Enum('POST_TWITTER', 'POST_INSTAGRAM', 'POST_FACEBOOK', 'REEL_SCRIPT', 'THREAD_TWITTER', 'INFOGRAFIA_COPY', 'COMUNICADO', name='formato_contenido'), nullable=False),
    sa.Column('tema', sa.String(length=255), nullable=False),
    sa.Column('tono', sa.String(length=50), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('prompt_usado', sa.Text(), nullable=False),
    sa.Column('plataforma_destino', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.Enum('BORRADOR', 'REVISADO', 'APROBADO', 'PUBLICADO', 'RECHAZADO', name='estado_contenido'), nullable=False),
    sa.Column('modelo_ia', sa.String(length=100), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('etiqueta_ia', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dirigente_id'], ['dirigentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generado_por_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contenidos_generados_dirigente_id'), 'contenidos_generados', ['dirigente_id'], unique=False)
    op.create_index(op.f('ix_contenidos_generados_org_id'), 'contenidos_generados', ['org_id'], unique=False)
    op.create_table('rutas_canvassing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('encuestador_id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('fecha_asignada', sa.Date(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'COMPLETADA', 'CANCELADA', name='estado_ruta'), nullable=False),
    sa.Column('distancia_total_km', sa.Float(), nullable=True),
    sa.Column('tiempo_estimado_min', sa.Integer(), nullable=True),
    sa.Column('puntos_total', sa.Integer(), nullable=False),
    sa.Column('puntos_completados', sa.Integer(), nullable=False),
    sa.Column('geometry_ruta', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encuestador_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones_electorales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rutas_canvassing_encuestador_id'), 'rutas_canvassing', ['encuestador_id'], unique=False)
    op.create_index(op.f('ix_rutas_canvassing_org_id'), 'rutas_canvassing', ['org_id'], unique=False)
    op.create_index(op.f('ix_rutas_canvassing_seccion_id'), 'rutas_canvassing', ['seccion_id'], unique=False)
    op.create_table('campana_mensajes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campana_id', sa.Integer(), nullable=False),
    sa.Column('ciudadano_id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'ENVIADO', 'ENTREGADO', 'LEIDO', 'RESPONDIDO', 'FALLIDO', name='estado_mensaje'), nullable=False),
    sa.Column('chatwoot_message_id', sa.String(length=100), nullable=True),
    sa.Column('enviado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entregado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('leido_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_mensaje', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campana_id'], ['campanas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadanos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campana_mensajes_campana_id'), 'campana_mensajes', ['campana_id'], unique=False)
    op.create_index(op.f('ix_campana_mensajes_chatwoot_message_id'), 'campana_mensajes', ['chatwoot_message_id'], unique=False)
    op.create_index(op.f('ix_campana_mensajes_ciudadano_id'), 'campana_mensajes', ['ciudadano_id'], unique=False)
    op.create_table('campana_segmentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('campana_id', sa.Integer(), nullable=False),
    sa.Column('filtro_seccion_id', sa.Integer(), nullable=True),
    sa.Column('filtro_intencion_voto', sa.String(length=50), nullable=True),
    sa.Column('filtro_edad_rango', sa.String(length=20), nullable=True),
    sa.Column('filtro_escolaridad', sa.String(length=50), nullable=True),
    sa.Column('filtro_es_simpatizante', sa.Boolean(), nullable=True),
    sa.Column('filtro_es_promotor', sa.Boolean(), nullable=True),
    sa.Column('filtro_score_min', sa.Float(), nullable=True),
    sa.Column('filtro_score_max', sa.Float(), nullable=True),
    sa.Column('ciudadanos_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campana_id'], ['campanas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campana_segmentos_campana_id'), 'campana_segmentos', ['campana_id'], unique=False)
    op.create_table('gastos_electorales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('dirigente_id', sa.Integer(), nullable=True),
    sa.Column('evento_id', sa.Integer(), nullable=True),
    sa.Column('concepto', sa.String(length=500), nullable=False),
    sa.Column('categoria', sa.Enum('PROPAGANDA', 'OPERATIVOS', 'GASTOS_PRODUCCION', 'TRANSPORTE', 'ALIMENTACION', 'ALQUILER_INMUEBLES', 'SERVICIOS_PERSONALES', 'PUBLICIDAD_REDES', 'OTROS', name='categoria_gasto_ine'), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_gasto', sa.Date(), nullable=False),
    sa.Column('proveedor', sa.String(length=255), nullable=True),
    sa.Column('factura_uuid', sa.String(length=36), nullable=True),
    sa.Column('evidencia_url', sa.String(length=500), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('aprobado_por_id', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dirigente_id'], ['dirigentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gastos_electorales_dirigente_id'), 'gastos_electorales', ['dirigente_id'], unique=False)
    op.create_index(op.f('ix_gastos_electorales_org_id'), 'gastos_electorales', ['org_id'], unique=False)
    op.create_table('puntos_ruta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ruta_id', sa.Integer(), nullable=False),
    sa.Column('ciudadano_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('visitado', sa.Boolean(), nullable=False),
    sa.Column('visitado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultado', sa.Enum('ENCUESTA_COMPLETADA', 'NO_EN_CASA', 'RECHAZO', 'REAGENDADO', 'DIRECCION_INCORRECTA', name='resultado_visita'), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadanos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ruta_id'], ['rutas_canvassing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_puntos_ruta_ciudadano_id'), 'puntos_ruta', ['ciudadano_id'], unique=False)
    op.create_index(op.f('ix_puntos_ruta_ruta_id'), 'puntos_ruta', ['ruta_id'], unique=False)
    op.create_table('solicitudes_ciudadanas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('ciudadano_id', sa.Integer(), nullable=True),
    sa.Column('seccion_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('QUEJA', 'PROPUESTA', 'SOLICITUD_INFO', 'REPORTE_PROBLEMA', 'DENUNCIA', 'AGRADECIMIENTO', name='tipo_solicitud'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('canal', sa.Enum('WHATSAPP', 'WEB', 'PRESENCIAL', 'TELEFONO', name='canal_origen'), nullable=False),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('colonia', sa.String(length=255), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('asignado_a_id', sa.Integer(), nullable=True),
    sa.Column('dirigente_responsable_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('RECIBIDA', 'EN_PROCESO', 'ASIGNADA', 'RESUELTA', 'CERRADA', 'RECHAZADA', name='estado_solicitud'), nullable=False),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('chatwoot_conversation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadanos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dirigente_responsable_id'], ['dirigentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones_electorales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitudes_ciudadanas_asignado_a_id'), 'solicitudes_ciudadanas', ['asignado_a_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_ciudadanas_ciudadano_id'), 'solicitudes_ciudadanas', ['ciudadano_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_ciudadanas_dirigente_responsable_id'), 'solicitudes_ciudadanas', ['dirigente_responsable_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_ciudadanas_org_id'), 'solicitudes_ciudadanas', ['org_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_ciudadanas_seccion_id'), 'solicitudes_ciudadanas', ['seccion_id'], unique=False)
    op.create_index(op.f('ix_solicitudes_ciudadanas_titulo'), 'solicitudes_ciudadanas', ['titulo'], unique=False)
    op.create_table('voter_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ciudadano_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('probabilidad_mc', sa.Float(), nullable=False),
    sa.Column('segmento', sa.Enum('PROMOTABLE', 'PERSUADIBLE', 'INDECISO', 'OPOSITOR', name='segmento_votante'), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('modelo_version', sa.String(length=50), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadanos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ciudadano_id', name='uq_voter_scores_ciudadano_id')
    )
    op.create_index(op.f('ix_voter_scores_ciudadano_id'), 'voter_scores', ['ciudadano_id'], unique=True)
    op.create_index(op.f('ix_voter_scores_org_id'), 'voter_scores', ['org_id'], unique=False)
    op.create_table('seguimiento_solicitudes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=100), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('estado_anterior', sa.String(length=50), nullable=True),
    sa.Column('estado_nuevo', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_ciudadanas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seguimiento_solicitudes_solicitud_id'), 'seguimiento_solicitudes', ['solicitud_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seguimiento_solicitudes_solicitud_id'), table_name='seguimiento_solicitudes')
    op.drop_table('seguimiento_solicitudes')
    op.drop_index(op.f('ix_voter_scores_org_id'), table_name='voter_scores')
    op.drop_index(op.f('ix_voter_scores_ciudadano_id'), table_name='voter_scores')
    op.drop_table('voter_scores')
    op.drop_index(op.f('ix_solicitudes_ciudadanas_titulo'), table_name='solicitudes_ciudadanas')
    op.drop_index(op.f('ix_solicitudes_ciudadanas_seccion_id'), table_name='solicitudes_ciudadanas')
    op.drop_index(op.f('ix_solicitudes_ciudadanas_org_id'), table_name='solicitudes_ciudadanas')
    op.drop_index(op.f('ix_solicitudes_ciudadanas_dirigente_responsable_id'), table_name='solicitudes_ciudadanas')
    op.drop_index(op.f('ix_solicitudes_ciudadanas_ciudadano_id'), table_name='solicitudes_ciudadanas')
    op.drop_index(op.f('ix_solicitudes_ciudadanas_asignado_a_id'), table_name='solicitudes_ciudadanas')
    op.drop_table('solicitudes_ciudadanas')
    op.drop_index(op.f('ix_puntos_ruta_ruta_id'), table_name='puntos_ruta')
    op.drop_index(op.f('ix_puntos_ruta_ciudadano_id'), table_name='puntos_ruta')
    op.drop_table('puntos_ruta')
    op.drop_index(op.f('ix_gastos_electorales_org_id'), table_name='gastos_electorales')
    op.drop_index(op.f('ix_gastos_electorales_dirigente_id'), table_name='gastos_electorales')
    op.drop_table('gastos_electorales')
    op.drop_index(op.f('ix_campana_segmentos_campana_id'), table_name='campana_segmentos')
    op.drop_table('campana_segmentos')
    op.drop_index(op.f('ix_campana_mensajes_ciudadano_id'), table_name='campana_mensajes')
    op.drop_index(op.f('ix_campana_mensajes_chatwoot_message_id'), table_name='campana_mensajes')
    op.drop_index(op.f('ix_campana_mensajes_campana_id'), table_name='campana_mensajes')
    op.drop_table('campana_mensajes')
    op.drop_index(op.f('ix_rutas_canvassing_seccion_id'), table_name='rutas_canvassing')
    op.drop_index(op.f('ix_rutas_canvassing_org_id'), table_name='rutas_canvassing')
    op.drop_index(op.f('ix_rutas_canvassing_encuestador_id'), table_name='rutas_canvassing')
    op.drop_table('rutas_canvassing')
    op.drop_index(op.f('ix_contenidos_generados_org_id'), table_name='contenidos_generados')
    op.drop_index(op.f('ix_contenidos_generados_dirigente_id'), table_name='contenidos_generados')
    op.drop_table('contenidos_generados')
    op.drop_index(op.f('ix_campanas_org_id'), table_name='campanas')
    op.drop_index(op.f('ix_campanas_nombre'), table_name='campanas')
    op.drop_index(op.f('ix_campanas_dirigente_id'), table_name='campanas')
    op.drop_table('campanas')
    op.drop_index(op.f('ix_alertas_compliance_org_id'), table_name='alertas_compliance')
    op.drop_table('alertas_compliance')
    # ### end Alembic commands ###
