"""f2.0 integration — campaigns, content, alerts, crm, api_keys

Revision ID: b2dd52dcf65e
Revises: 77a614d10263
Create Date: 2026-04-03 23:06:00.850399
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2dd52dcf65e'
down_revision: Union[str, None] = '77a614d10263'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ia_content_registry',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('tipo_contenido', sa.String(length=100), nullable=False),
    sa.Column('referencia_tabla', sa.String(length=100), nullable=False),
    sa.Column('referencia_id', sa.String(length=100), nullable=False),
    sa.Column('modelo_ia', sa.String(length=100), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ia_content_registry_org_id'), 'ia_content_registry', ['org_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_org_id'), 'api_keys', ['org_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('segmentacion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tipo_nudge', sa.String(length=50), nullable=True),
    sa.Column('total_destinatarios', sa.Integer(), nullable=False),
    sa.Column('enviados', sa.Integer(), nullable=False),
    sa.Column('entregados', sa.Integer(), nullable=False),
    sa.Column('leidos', sa.Integer(), nullable=False),
    sa.Column('respondidos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('chatwoot_campaign_id', sa.String(length=100), nullable=True),
    sa.Column('programado_para', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_org_id'), 'campaigns', ['org_id'], unique=False)
    op.create_table('contenido_piezas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('dirigente_id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.String(length=500), nullable=False),
    sa.Column('contexto', sa.Text(), nullable=True),
    sa.Column('tono', sa.String(length=50), nullable=False),
    sa.Column('variantes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('modelo_ia', sa.String(length=100), nullable=False),
    sa.Column('prompt_usado', sa.Text(), nullable=False),
    sa.Column('tokens_usados', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('aprobado_por', sa.Integer(), nullable=True),
    sa.Column('aprobado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('programacion', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprobado_por'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dirigente_id'], ['dirigentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contenido_piezas_dirigente_id'), 'contenido_piezas', ['dirigente_id'], unique=False)
    op.create_index(op.f('ix_contenido_piezas_org_id'), 'contenido_piezas', ['org_id'], unique=False)
    op.create_table('alertas_crisis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('post_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['perfil_id'], ['social_profiles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_crisis_org_id'), 'alertas_crisis', ['org_id'], unique=False)
    op.create_index(op.f('ix_alertas_crisis_perfil_id'), 'alertas_crisis', ['perfil_id'], unique=False)
    op.create_table('crm_interacciones',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('ciudadano_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('canal', sa.String(length=50), nullable=True),
    sa.Column('resultado', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('referencia_tipo', sa.String(length=50), nullable=True),
    sa.Column('referencia_id', sa.String(length=100), nullable=True),
    sa.Column('promotor_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadanos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_interacciones_ciudadano_id'), 'crm_interacciones', ['ciudadano_id'], unique=False)
    op.create_index(op.f('ix_crm_interacciones_org_id'), 'crm_interacciones', ['org_id'], unique=False)
    op.create_table('voter_scores_integration',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('ciudadano_id', sa.Integer(), nullable=False),
    sa.Column('score_favorable', sa.Float(), nullable=False),
    sa.Column('score_persuadible', sa.Float(), nullable=False),
    sa.Column('score_asistencia', sa.Float(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('modelo_version', sa.String(length=50), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadanos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ciudadano_id', name='uq_voter_scores_integration_ciudadano_id')
    )
    op.create_index(op.f('ix_voter_scores_integration_ciudadano_id'), 'voter_scores_integration', ['ciudadano_id'], unique=True)
    op.create_index(op.f('ix_voter_scores_integration_org_id'), 'voter_scores_integration', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voter_scores_integration_org_id'), table_name='voter_scores_integration')
    op.drop_index(op.f('ix_voter_scores_integration_ciudadano_id'), table_name='voter_scores_integration')
    op.drop_table('voter_scores_integration')
    op.drop_index(op.f('ix_crm_interacciones_org_id'), table_name='crm_interacciones')
    op.drop_index(op.f('ix_crm_interacciones_ciudadano_id'), table_name='crm_interacciones')
    op.drop_table('crm_interacciones')
    op.drop_index(op.f('ix_alertas_crisis_perfil_id'), table_name='alertas_crisis')
    op.drop_index(op.f('ix_alertas_crisis_org_id'), table_name='alertas_crisis')
    op.drop_table('alertas_crisis')
    op.drop_index(op.f('ix_contenido_piezas_org_id'), table_name='contenido_piezas')
    op.drop_index(op.f('ix_contenido_piezas_dirigente_id'), table_name='contenido_piezas')
    op.drop_table('contenido_piezas')
    op.drop_index(op.f('ix_campaigns_org_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_api_keys_org_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_ia_content_registry_org_id'), table_name='ia_content_registry')
    op.drop_table('ia_content_registry')
    # ### end Alembic commands ###
