"""initial schema — all 12 models

Revision ID: ecb44c21a495
Revises: 
Create Date: 2026-04-03 19:34:40.474131
"""
from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecb44c21a495'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Ensure PostGIS extension exists (init.sql only runs on first DB creation)
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competidores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('partido', sa.String(length=50), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=False),
    sa.Column('es_rival', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competidores_nombre'), 'competidores', ['nombre'], unique=False)
    op.create_table('organizaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('PARTIDO', 'CANDIDATURA', 'ONG', 'GOBIERNO', name='tipo_organizacion'), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('programas_sociales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('dependencia', sa.String(length=255), nullable=False),
    sa.Column('nivel_gobierno', sa.Enum('FEDERAL', 'ESTATAL', 'MUNICIPAL', name='nivel_gobierno'), nullable=False),
    sa.Column('presupuesto_anual', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programas_sociales_nombre'), 'programas_sociales', ['nombre'], unique=False)
    op.create_table('secciones_electorales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seccion', sa.String(length=10), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('distrito_federal', sa.String(length=10), nullable=False),
    sa.Column('distrito_local', sa.String(length=10), nullable=False),
    sa.Column('municipio', sa.String(length=200), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secciones_electorales_estado'), 'secciones_electorales', ['estado'], unique=False)
    op.create_index(op.f('ix_secciones_electorales_seccion'), 'secciones_electorales', ['seccion'], unique=True)
    op.create_table('competidor_social_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('competidor_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('TWITTER', 'INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'BLUESKY', name='platform_enum'), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['competidor_id'], ['competidores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competidor_social_profiles_competidor_id'), 'competidor_social_profiles', ['competidor_id'], unique=False)
    op.create_table('dirigentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=255), nullable=False),
    sa.Column('partido', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=100), nullable=False),
    sa.Column('municipio', sa.String(length=200), nullable=True),
    sa.Column('seccion_electoral', sa.String(length=10), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dirigentes_estado'), 'dirigentes', ['estado'], unique=False)
    op.create_index(op.f('ix_dirigentes_full_name'), 'dirigentes', ['full_name'], unique=False)
    op.create_index(op.f('ix_dirigentes_org_id'), 'dirigentes', ['org_id'], unique=False)
    op.create_table('programa_beneficiarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('programa_id', sa.Integer(), nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('beneficiarios_count', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('fecha_actualizacion', sa.Date(), nullable=False),
    sa.Column('fuente_datos', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['programa_id'], ['programas_sociales.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones_electorales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programa_beneficiarios_programa_id'), 'programa_beneficiarios', ['programa_id'], unique=False)
    op.create_index(op.f('ix_programa_beneficiarios_seccion_id'), 'programa_beneficiarios', ['seccion_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'FIELD_OPERATOR', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)
    op.create_table('ciudadanos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=255), nullable=False),
    sa.Column('apellido_materno', sa.String(length=255), nullable=True),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('edad_rango', sa.Enum('E_18_25', 'E_26_35', 'E_36_45', 'E_46_55', 'E_56_65', 'E_65_PLUS', name='rango_edad'), nullable=False),
    sa.Column('genero', sa.Enum('M', 'F', 'OTRO', 'NO_ESPECIFICADO', name='genero'), nullable=False),
    sa.Column('nivel_interes', sa.Enum('ALTO', 'MEDIO', 'BAJO', 'DESCONOCIDO', name='nivel_interes'), nullable=False),
    sa.Column('es_simpatizante_mc', sa.Boolean(), nullable=False),
    sa.Column('es_promotor', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('registrado_por_id', sa.Integer(), nullable=False),
    sa.Column('intencion_voto', sa.Enum('MC', 'MORENA', 'PAN', 'PRI', 'PVEM', 'PT', 'OTRO', 'INDECISO', 'NO_RESPONDE', name='intencion_voto_ciudadano'), nullable=True),
    sa.Column('programas_sociales', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('problematicas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ubicacion', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('colonia', sa.String(length=255), nullable=True),
    sa.Column('codigo_postal', sa.String(length=5), nullable=True),
    sa.Column('escolaridad', sa.Enum('SIN_ESTUDIOS', 'PRIMARIA', 'SECUNDARIA', 'PREPARATORIA', 'UNIVERSIDAD', 'POSGRADO', name='escolaridad'), nullable=True),
    sa.Column('foto_ine_url', sa.String(length=500), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['registrado_por_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones_electorales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ciudadanos_nombre'), 'ciudadanos', ['nombre'], unique=False)
    op.create_index(op.f('ix_ciudadanos_org_id'), 'ciudadanos', ['org_id'], unique=False)
    op.create_index(op.f('ix_ciudadanos_seccion_id'), 'ciudadanos', ['seccion_id'], unique=False)
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('MITIN', 'REUNION', 'RECORRIDO', 'CAPACITACION', 'ASAMBLEA', 'OTRO', name='tipo_evento'), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lugar', sa.String(length=500), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('seccion_id', sa.Integer(), nullable=True),
    sa.Column('dirigente_id', sa.Integer(), nullable=True),
    sa.Column('organizador_id', sa.Integer(), nullable=False),
    sa.Column('asistentes_esperados', sa.Integer(), nullable=True),
    sa.Column('asistentes_reales', sa.Integer(), nullable=True),
    sa.Column('recursos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nuevos_simpatizantes', sa.Integer(), nullable=True),
    sa.Column('costo_total', sa.Float(), nullable=True),
    sa.Column('costo_por_adquisicion', sa.Float(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('PROGRAMADO', 'EN_CURSO', 'COMPLETADO', 'CANCELADO', name='estado_evento'), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dirigente_id'], ['dirigentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organizador_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones_electorales.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_dirigente_id'), 'eventos', ['dirigente_id'], unique=False)
    op.create_index(op.f('ix_eventos_org_id'), 'eventos', ['org_id'], unique=False)
    op.create_index(op.f('ix_eventos_seccion_id'), 'eventos', ['seccion_id'], unique=False)
    op.create_index(op.f('ix_eventos_titulo'), 'eventos', ['titulo'], unique=False)
    op.create_table('intencion_voto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('dirigente_id', sa.Integer(), nullable=True),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('muestra', sa.Integer(), nullable=False),
    sa.Column('a_favor', sa.Float(), nullable=False),
    sa.Column('en_contra', sa.Float(), nullable=False),
    sa.Column('indeciso', sa.Float(), nullable=False),
    sa.Column('no_responde', sa.Float(), nullable=False),
    sa.Column('fecha_encuesta', sa.Date(), nullable=False),
    sa.Column('capturado_por_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capturado_por_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dirigente_id'], ['dirigentes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones_electorales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intencion_voto_dirigente_id'), 'intencion_voto', ['dirigente_id'], unique=False)
    op.create_index(op.f('ix_intencion_voto_seccion_id'), 'intencion_voto', ['seccion_id'], unique=False)
    op.create_table('planes_ia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dirigente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('DIAGNOSTICO', 'CONSOLIDACION', 'CRISIS', 'CONTENIDO', name='tipo_plan_enum'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('modelo_ia', sa.String(length=100), nullable=False),
    sa.Column('prompt_usado', sa.Text(), nullable=False),
    sa.Column('datos_entrada', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generado_por_id', sa.Integer(), nullable=False),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dirigente_id'], ['dirigentes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['generado_por_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planes_ia_dirigente_id'), 'planes_ia', ['dirigente_id'], unique=False)
    op.create_table('social_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dirigente_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('TWITTER', 'INSTAGRAM', 'FACEBOOK', 'TIKTOK', 'YOUTUBE', 'BLUESKY', name='platform_enum'), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('last_scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dirigente_id'], ['dirigentes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_profiles_dirigente_id'), 'social_profiles', ['dirigente_id'], unique=False)
    op.create_table('encuestas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ciudadano_id', sa.Integer(), nullable=False),
    sa.Column('encuestador_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('seccion_id', sa.Integer(), nullable=False),
    sa.Column('intencion_voto', sa.Enum('MC', 'MORENA', 'PAN', 'PRI', 'PVEM', 'PT', 'OTRO', 'INDECISO', 'NO_RESPONDE', name='intencion_voto_ciudadano'), nullable=False),
    sa.Column('nivel_certeza', sa.Enum('ALTA', 'MEDIA', 'BAJA', name='nivel_certeza'), nullable=False),
    sa.Column('motivacion', sa.Text(), nullable=True),
    sa.Column('problematicas_detectadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ubicacion_captura', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('fecha_encuesta', sa.Date(), nullable=False),
    sa.Column('duracion_minutos', sa.Integer(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadanos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['encuestador_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organizaciones.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seccion_id'], ['secciones_electorales.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encuestas_ciudadano_id'), 'encuestas', ['ciudadano_id'], unique=False)
    op.create_index(op.f('ix_encuestas_org_id'), 'encuestas', ['org_id'], unique=False)
    op.create_index(op.f('ix_encuestas_seccion_id'), 'encuestas', ['seccion_id'], unique=False)
    op.create_table('evento_asistentes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('ciudadano_id', sa.Integer(), nullable=False),
    sa.Column('confirmado', sa.Boolean(), nullable=False),
    sa.Column('asistio', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ciudadano_id'], ['ciudadanos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evento_id'], ['eventos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_asistentes_ciudadano_id'), 'evento_asistentes', ['ciudadano_id'], unique=False)
    op.create_index(op.f('ix_evento_asistentes_evento_id'), 'evento_asistentes', ['evento_id'], unique=False)
    op.create_table('metricas_sociales',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('followers_count', sa.Integer(), nullable=False),
    sa.Column('following_count', sa.Integer(), nullable=False),
    sa.Column('posts_count', sa.Integer(), nullable=False),
    sa.Column('engagement_rate_avg', sa.Float(), nullable=True),
    sa.Column('followers_delta', sa.Integer(), nullable=False),
    sa.Column('posts_delta', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'periodo', name='uq_metrica_profile_periodo')
    )
    op.create_index(op.f('ix_metricas_sociales_profile_id'), 'metricas_sociales', ['profile_id'], unique=False)
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('post_type', sa.Enum('TEXT', 'IMAGE', 'VIDEO', 'REEL', 'STORY', 'CAROUSEL', name='post_type_enum'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', name='sentiment_label_enum'), nullable=True),
    sa.Column('emotions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_political', sa.Boolean(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['social_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_post_id')
    )
    op.create_index(op.f('ix_social_posts_profile_id'), 'social_posts', ['profile_id'], unique=False)
    op.create_table('sentiment_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_label', sa.Enum('POSITIVE', 'NEGATIVE', 'NEUTRAL', 'MIXED', name='sentiment_label_enum'), nullable=False),
    sa.Column('emotions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_toxic', sa.Boolean(), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=False),
    sa.Column('propaganda_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentiment_analyses_post_id'), 'sentiment_analyses', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentiment_analyses_post_id'), table_name='sentiment_analyses')
    op.drop_table('sentiment_analyses')
    op.drop_index(op.f('ix_social_posts_profile_id'), table_name='social_posts')
    op.drop_table('social_posts')
    op.drop_index(op.f('ix_metricas_sociales_profile_id'), table_name='metricas_sociales')
    op.drop_table('metricas_sociales')
    op.drop_index(op.f('ix_evento_asistentes_evento_id'), table_name='evento_asistentes')
    op.drop_index(op.f('ix_evento_asistentes_ciudadano_id'), table_name='evento_asistentes')
    op.drop_table('evento_asistentes')
    op.drop_index(op.f('ix_encuestas_seccion_id'), table_name='encuestas')
    op.drop_index(op.f('ix_encuestas_org_id'), table_name='encuestas')
    op.drop_index(op.f('ix_encuestas_ciudadano_id'), table_name='encuestas')
    op.drop_table('encuestas')
    op.drop_index(op.f('ix_social_profiles_dirigente_id'), table_name='social_profiles')
    op.drop_table('social_profiles')
    op.drop_index(op.f('ix_planes_ia_dirigente_id'), table_name='planes_ia')
    op.drop_table('planes_ia')
    op.drop_index(op.f('ix_intencion_voto_seccion_id'), table_name='intencion_voto')
    op.drop_index(op.f('ix_intencion_voto_dirigente_id'), table_name='intencion_voto')
    op.drop_table('intencion_voto')
    op.drop_index(op.f('ix_eventos_titulo'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_seccion_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_org_id'), table_name='eventos')
    op.drop_index(op.f('ix_eventos_dirigente_id'), table_name='eventos')
    op.drop_table('eventos')
    op.drop_index(op.f('ix_ciudadanos_seccion_id'), table_name='ciudadanos')
    op.drop_index(op.f('ix_ciudadanos_org_id'), table_name='ciudadanos')
    op.drop_index(op.f('ix_ciudadanos_nombre'), table_name='ciudadanos')
    op.drop_table('ciudadanos')
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_programa_beneficiarios_seccion_id'), table_name='programa_beneficiarios')
    op.drop_index(op.f('ix_programa_beneficiarios_programa_id'), table_name='programa_beneficiarios')
    op.drop_table('programa_beneficiarios')
    op.drop_index(op.f('ix_dirigentes_org_id'), table_name='dirigentes')
    op.drop_index(op.f('ix_dirigentes_full_name'), table_name='dirigentes')
    op.drop_index(op.f('ix_dirigentes_estado'), table_name='dirigentes')
    op.drop_table('dirigentes')
    op.drop_index(op.f('ix_competidor_social_profiles_competidor_id'), table_name='competidor_social_profiles')
    op.drop_table('competidor_social_profiles')
    op.drop_index(op.f('ix_secciones_electorales_seccion'), table_name='secciones_electorales')
    op.drop_index(op.f('ix_secciones_electorales_estado'), table_name='secciones_electorales')
    op.drop_table('secciones_electorales')
    op.drop_index(op.f('ix_programas_sociales_nombre'), table_name='programas_sociales')
    op.drop_table('programas_sociales')
    op.drop_table('organizaciones')
    op.drop_index(op.f('ix_competidores_nombre'), table_name='competidores')
    op.drop_table('competidores')
    # ### end Alembic commands ###
